## Basic functions testing from quadratic.py

In [1]:
import numpy as np

In [2]:
from quadratic import *

In [12]:
ncel = 64

x = np.random.normal(0,10,(ncel,ncel,ncel)).astype(np.float32)
b = np.random.normal(0,10,(ncel,ncel,ncel)).astype(np.float32)

In [13]:
h = np.float32(1./16)

In [21]:
C2 = np.float32(-1.5)
C4 = np.float32(0.1)
alphaB = np.float32(0.1)
alphaM = np.float32(0.3)
H = np.float32(1.)
a = np.float32(1.)
M = np.float32(1.)

In [6]:
res = operator(x,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [7]:
ix = np.int32(1)
iy = ix
iz = ix

s1 = solution_quadratic_equation(x,b[ix,iy,iz],ix,iy,iz,h,C2,C4,alphaB,alphaM,H,a,M)

In [8]:
s1

0.29026177525520325

In [22]:
xo = np.copy(x)

In [23]:
jacobi(x,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [26]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,M,600)

In [27]:
x

array([[[ 6.611796  ,  2.755548  , -2.5308566 , ...,  7.615201  ,
         10.419323  ,  2.6414778 ],
        [ 3.9567287 ,  1.3290159 ,  6.8973083 , ...,  6.2316046 ,
          4.030776  , -0.5418774 ],
        [ 2.0112662 ,  3.0227392 , 11.128209  , ...,  8.12572   ,
          5.612854  ,  5.4003105 ],
        ...,
        [ 8.9403    ,  3.5383925 ,  6.9055295 , ..., 11.667647  ,
          8.127632  ,  3.25879   ],
        [ 5.814212  ,  0.41433135,  6.6940613 , ...,  9.947889  ,
          4.88264   , 13.845016  ],
        [-1.4929024 ,  7.1530747 ,  4.344763  , ...,  4.156934  ,
          3.6008625 ,  8.722534  ]],

       [[ 5.370474  ,  9.140543  ,  2.563501  , ...,  7.0289865 ,
          5.9323354 ,  3.0302966 ],
        [-2.541978  ,  5.003707  ,  2.3461044 , ..., 12.351959  ,
         -4.0643945 ,  7.2689095 ],
        [ 7.1433005 ,  4.0511036 ,  2.881611  , ...,  1.787108  ,
          8.783301  , -5.6268167 ],
        ...,
        [ 2.2063155 ,  6.3748817 ,  6.039962  , ...,  

In [19]:
xo

array([[[15.098835 , 15.098076 , 15.087799 , ..., 15.096634 ,
         15.145648 , 15.07809  ],
        [15.017386 , 15.069138 , 15.087268 , ..., 15.182371 ,
         15.0092   , 15.104117 ],
        [15.071401 , 15.006938 , 15.049827 , ..., 14.968915 ,
         15.134294 , 14.957919 ],
        ...,
        [15.319873 , 15.191027 , 15.311997 , ..., 15.222291 ,
         15.350076 , 15.196053 ],
        [15.153344 , 15.239797 , 15.151959 , ..., 15.279832 ,
         15.179124 , 15.251191 ],
        [15.159235 , 15.117059 , 15.186907 , ..., 15.191592 ,
         15.172436 , 15.136546 ]],

       [[15.045848 , 15.11215  , 15.099208 , ..., 15.189928 ,
         15.046757 , 15.13428  ],
        [15.1029625, 15.018242 , 15.0876   , ..., 14.999822 ,
         15.15153  , 14.98338  ],
        [14.961469 , 15.078198 , 15.043192 , ..., 15.195355 ,
         14.950116 , 15.1166725],
        ...,
        [15.219911 , 15.264752 , 15.224848 , ..., 15.299265 ,
         15.219009 , 15.274196 ],
        [15.

In [13]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,M,6)

In [14]:
xo

array([[[1.51646  , 1.5293015, 1.5379088, ..., 1.565988 , 1.5790473,
         1.5019006],
        [1.5221701, 1.5352731, 1.5438478, ..., 1.5713122, 1.5842962,
         1.507192 ],
        [1.5259612, 1.5389106, 1.5473132, ..., 1.57535  , 1.5882149,
         1.5109271],
        ...,
        [1.582018 , 1.5922978, 1.5997967, ..., 1.635401 , 1.6496521,
         1.5697236],
        [1.5906371, 1.6016508, 1.6094445, ..., 1.643808 , 1.657653 ,
         1.5777106],
        [1.5084704, 1.5206102, 1.528996 , ..., 1.5589355, 1.5721589,
         1.4946926]],

       [[1.5287266, 1.5401728, 1.5481044, ..., 1.5815368, 1.5938127,
         1.5159193],
        [1.5325515, 1.5447329, 1.5531917, ..., 1.5853492, 1.5972308,
         1.5190597],
        [1.5343289, 1.5470479, 1.556024 , ..., 1.5871077, 1.5988019,
         1.5202266],
        ...,
        [1.593716 , 1.603193 , 1.6103699, ..., 1.649379 , 1.6630946,
         1.5825589],
        [1.6034409, 1.6132876, 1.6204097, ..., 1.6590571, 1.6723608,
   

In [15]:
xn = np.random.rand(16,16,16).astype(np.float32)

In [16]:

res1 = residual(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [17]:
op1 = operator(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [18]:
res1[0,0,0]

-859.05853

In [19]:
op1[0,0,0]

859.05853

In [20]:
reserr = residual_error(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [21]:
reserr

334405.75

In [22]:
terr = truncation_error(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [23]:
terr

79485.75

In [25]:
phi0 = initialise_potential(b,h,C2,alphaB,alphaM,a,M)

In [26]:
phi0

array([[[-3.14360630e-04, -3.98655393e-04, -3.13039083e-04, ...,
         -3.40610277e-04, -9.39068923e-05, -4.37979215e-05],
        [-2.46582873e-04, -4.24688333e-04, -3.88286106e-04, ...,
         -2.83961144e-05, -2.80011416e-04, -1.60826734e-04],
        [-5.65444279e-05, -2.00757218e-04, -2.36356369e-04, ...,
         -1.17547752e-04, -7.74524960e-05, -1.02697937e-04],
        ...,
        [-1.82913354e-04, -2.02446143e-04, -3.97964235e-04, ...,
         -2.07170699e-04, -2.30238526e-04, -1.82500924e-04],
        [-4.30655316e-04, -2.55116262e-04, -7.70488623e-05, ...,
         -3.11201817e-04, -1.54897803e-04, -3.28888622e-04],
        [-2.14818268e-04, -2.94344674e-04, -3.61235172e-04, ...,
         -3.66624095e-04, -3.08736344e-04, -1.67308797e-04]],

       [[-3.11168958e-04, -2.66370480e-04, -7.77180539e-05, ...,
         -2.93892575e-04, -3.51389230e-04, -3.23399669e-04],
        [-4.35457696e-05, -1.90863488e-04, -1.85480952e-04, ...,
         -4.25933569e-04, -2.18197601e

## Additional field testing

In [28]:
import pandas as pd
import cosmotable
import utils

In [29]:
param = pd.Series({
    "theory": "eft",
    "alphaB0": 0.1,
    "alphaM0": 0.3,
    "H0": 70.0,
    "Om_m": 0.3,
    "T_cmb": 2.726,
    "N_eff": 3.044,
    "w0": -1.0,
    "wa": 0.0,
    "base": "./",
    "extra": "test",
    "aexp":1,
    "boxlen":100,
    "npart":256**3,
    "compute_additional_field":True,
    "ncoarse":8,
    "Npre":4,
    "Npost":1
    })

In [30]:
tables = cosmotable.generate(param)
utils.set_units(param)

/opt/anaconda3/lib/python3.12/site-packages/astropy/cosmology/flrw/w0wacdm.py:195: RuntimeWarning: invalid value encountered in scalar divide
  return zp1 ** (3 * (1 + self._w0 + self._wa)) * exp(-3 * self._wa * z / zp1)


In [31]:
param

theory                                                              eft
alphaB0                                                             0.1
alphaM0                                                             0.3
H0                                                                 70.0
Om_m                                                                0.3
T_cmb                                                             2.726
N_eff                                                             3.044
w0                                                                 -1.0
wa                                                                  0.0
base                                                                 ./
extra                                                              test
aexp                                                                  1
boxlen                                                              100
npart                                                          1

In [32]:
import eftcalcs

In [33]:
eft_quantities = eftcalcs.geteft(param,tables)

In [41]:
potential = np.empty(0, dtype=np.float32)
density = np.random.normal(0,10,(256,256,256)).astype(np.float32)
h = 1./256

param["alphaB"] = eft_quantities[0]
param["alphaM"] = eft_quantities[1]
param["C2"] = eft_quantities[2]
param["C4"] = eft_quantities[3]
param["H"] = eft_quantities[4]
param["M"] = eft_quantities[5]

In [42]:
import solver

In [43]:
phi = solver.initialise_potential(potential,density,h,param,tables)

In [44]:
phi = solver.get_additional_field(phi,density,h,param,tables)

[0.09999999999999999, 0.3, 1.1930805152998332, 0.2, 0.9999999999999999, 0.9672311250534926]
Mean chi: 0, dens: -1.0002e+00, stdev: 9.9973e+00
op111: 8.7361e-05


### initialise_potential and get_additional_field work: 13 Jan 25

In [45]:
phi.shape

(256, 256, 256)

In [46]:
phi

array([[[10.434296 , 10.43681  , 10.435273 , ..., 10.435791 ,
         10.435626 , 10.436086 ],
        [10.436256 , 10.434516 , 10.437109 , ..., 10.436857 ,
         10.435017 , 10.436183 ],
        [10.435895 , 10.435483 , 10.435841 , ..., 10.435246 ,
         10.436396 , 10.435314 ],
        ...,
        [10.435275 , 10.437291 , 10.435706 , ..., 10.435466 ,
         10.435054 , 10.437675 ],
        [10.436435 , 10.43568  , 10.435018 , ..., 10.436432 ,
         10.436882 , 10.435058 ],
        [10.436623 , 10.434699 , 10.4368105, ..., 10.43555  ,
         10.435502 , 10.435559 ]],

       [[10.43701  , 10.435647 , 10.4361   , ..., 10.435248 ,
         10.43589  , 10.434634 ],
        [10.435212 , 10.436853 , 10.435337 , ..., 10.435937 ,
         10.4354105, 10.435938 ],
        [10.435553 , 10.436063 , 10.435933 , ..., 10.43697  ,
         10.435967 , 10.435845 ],
        ...,
        [10.436793 , 10.435085 , 10.435571 , ..., 10.435349 ,
         10.436941 , 10.4345875],
        [10.