## Basic functions testing from quadratic.py

In [1]:
import numpy as np

In [2]:
from quadratic import *

In [3]:
ncel = 64

x = np.random.normal(0,10,(ncel,ncel,ncel)).astype(np.float32)
b = np.random.normal(0,10,(ncel,ncel,ncel)).astype(np.float32)

In [4]:
h = np.float32(1./16)

In [5]:
C2 = np.float32(-1.5)
C4 = np.float32(0.1)
alphaB = np.float32(0.1)
alphaM = np.float32(0.3)
H = np.float32(1.)
a = np.float32(1.)
M = np.float32(1.)

In [6]:
res = operator(x,b,h,C2,C4,alphaB,alphaM,H,a)

In [7]:
ix = np.int32(1)
iy = ix
iz = ix

s1 = solution_quadratic_equation(x,b[ix,iy,iz],ix,iy,iz,h,C2,C4,alphaB,alphaM,H,a)

In [8]:
s1

-0.16743667423725128

In [9]:
xo = np.copy(x)

In [10]:
jacobi(x,b,h,C2,C4,alphaB,alphaM,H,a)

In [11]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,600)

In [12]:
x

array([[[ 4.2923565 ,  0.6919997 ,  0.3643611 , ...,  4.9975433 ,
          3.6214283 , -3.0157115 ],
        [-4.614212  ,  2.5871797 , -2.2002304 , ..., 11.566389  ,
          9.723913  ,  1.6624899 ],
        [ 7.8246775 , -6.023779  ,  7.589352  , ..., 14.509917  ,
          6.3199053 ,  0.65679395],
        ...,
        [ 1.1620921 ,  0.9592265 ,  4.480108  , ...,  6.1599164 ,
          6.010249  ,  1.4344215 ],
        [-0.8799262 ,  0.7607799 , -0.06899644, ..., -0.8524988 ,
          3.4271286 ,  8.227349  ],
        [-2.371562  ,  8.213204  , -2.1217234 , ...,  7.911153  ,
          1.2267183 ,  4.9191084 ]],

       [[-1.3118782 ,  4.7270083 , -2.7774882 , ...,  9.151694  ,
          0.81464475,  7.458765  ],
        [12.580771  , -0.16743667,  2.4576974 , ...,  7.675511  ,
         10.191692  ,  2.3181646 ],
        [ 1.1881638 ,  7.4380674 ,  4.2660766 , ...,  4.2212553 ,
          2.9245906 ,  8.501877  ],
        ...,
        [-0.47793785, -2.242592  , -2.6777866 , ..., -

In [13]:
xo

array([[[8.317195 , 8.338353 , 8.311817 , ..., 8.3324175, 8.3242235,
         8.3370905],
        [8.338133 , 8.316514 , 8.34078  , ..., 8.3253355, 8.334511 ,
         8.320984 ],
        [8.318015 , 8.340699 , 8.3140745, ..., 8.331997 , 8.321969 ,
         8.333693 ],
        ...,
        [8.33556  , 8.311585 , 8.337639 , ..., 8.320566 , 8.330835 ,
         8.313437 ],
        [8.314782 , 8.336988 , 8.308085 , ..., 8.329835 , 8.319368 ,
         8.333931 ],
        [8.337736 , 8.311855 , 8.338394 , ..., 8.324001 , 8.333826 ,
         8.3168545]],

       [[8.340884 , 8.313074 , 8.343057 , ..., 8.326006 , 8.337518 ,
         8.318432 ],
        [8.316762 , 8.3421545, 8.314602 , ..., 8.334518 , 8.322017 ,
         8.338857 ],
        [8.34095  , 8.317556 , 8.344974 , ..., 8.325375 , 8.334225 ,
         8.318673 ],
        ...,
        [8.312175 , 8.337956 , 8.310381 , ..., 8.331383 , 8.318692 ,
         8.334494 ],
        [8.336706 , 8.310377 , 8.341574 , ..., 8.321745 , 8.335183 ,
   

In [14]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,6)

In [15]:
xo

array([[[8.317451 , 8.337565 , 8.312121 , ..., 8.3319   , 8.324301 ,
         8.336334 ],
        [8.337251 , 8.316766 , 8.339856 , ..., 8.325739 , 8.333711 ,
         8.321157 ],
        [8.318067 , 8.339745 , 8.31437  , ..., 8.331199 , 8.321989 ,
         8.333013 ],
        ...,
        [8.334865 , 8.312169 , 8.337148 , ..., 8.320534 , 8.330071 ,
         8.313253 ],
        [8.315253 , 8.335916 , 8.3085575, ..., 8.329475 , 8.31972  ,
         8.333042 ],
        [8.337341 , 8.3123865, 8.33739  , ..., 8.324061 , 8.3331785,
         8.317303 ]],

       [[8.340041 , 8.313526 , 8.342236 , ..., 8.326162 , 8.336563 ,
         8.318769 ],
        [8.317075 , 8.341056 , 8.314821 , ..., 8.3338175, 8.322338 ,
         8.337907 ],
        [8.3399725, 8.317488 , 8.344164 , ..., 8.325638 , 8.333364 ,
         8.318723 ],
        ...,
        [8.312342 , 8.337377 , 8.310593 , ..., 8.330596 , 8.318883 ,
         8.333668 ],
        [8.335778 , 8.310644 , 8.340593 , ..., 8.32187  , 8.334028 ,
   

In [16]:
xn = np.random.rand(16,16,16).astype(np.float32)

In [17]:

res1 = residual(xn,b,h,C2,C4,alphaB,alphaM,H,a)

In [18]:
op1 = operator(xn,b,h,C2,C4,alphaB,alphaM,H,a)

In [19]:
res1[0,0,0]

899.94293

In [20]:
op1[0,0,0]

-899.94293

In [21]:
reserr = residual_error(xn,b,h,C2,C4,alphaB,alphaM,H,a)

In [22]:
reserr

322621.5

In [23]:
terr = truncation_error(xn,b,h,C2,C4,alphaB,alphaM,H,a)

In [24]:
terr

75244.8984375

In [25]:
phi0 = initialise_potential(b,h,C2,alphaB,alphaM)

In [26]:
phi0

array([[[-3.82420234e-03,  4.71579097e-03, -4.81083803e-03, ...,
         -3.22350324e-03, -1.46255959e-02, -9.90958186e-04],
        [ 5.78510109e-03, -1.16578946e-02,  6.15560636e-03, ...,
         -1.38947275e-03, -3.67676490e-04, -1.14101144e-02],
        [-8.80450102e-07, -5.42303920e-03,  4.18725703e-03, ...,
         -1.24466261e-02,  1.21481414e-03,  9.20944940e-03],
        ...,
        [-7.80755468e-03, -8.10239743e-03,  9.15126409e-04, ...,
          1.04949428e-02,  5.21062315e-03,  1.54793486e-02],
        [-7.83655979e-03,  1.84533303e-03,  1.02045049e-03, ...,
         -2.84578511e-03, -2.73222290e-03, -2.90259533e-03],
        [-7.28031015e-03,  5.40990790e-04,  1.63690606e-03, ...,
         -5.17200958e-03,  1.23699394e-03,  9.29485634e-03]],

       [[-9.21302382e-03,  4.07062192e-03, -2.58994754e-03, ...,
         -1.51271271e-02, -4.56690090e-03,  1.31827698e-03],
        [ 6.05807360e-03,  4.57554869e-03, -7.00050453e-03, ...,
         -7.83439446e-03, -2.19877227e

## Additional field testing

In [27]:
import pandas as pd
import cosmotable
import utils

In [28]:
param = pd.Series({
    "theory": "eft",
    "alphaB0": 0.1,
    "alphaM0": 0.3,
    "H0": 70.0,
    "Om_m": 0.3,
    "T_cmb": 2.726,
    "N_eff": 3.044,
    "w0": -1.0,
    "wa": 0.0,
    "base": "./",
    "extra": "test",
    "aexp":1,
    "boxlen":100,
    "npart":256**3,
    "compute_additional_field":True,
    "ncoarse":8,
    "Npre":4,
    "Npost":1
    })

In [37]:
tables = cosmotable.generate(param)
utils.set_units(param)
param['parametrized_mu_z'] = 0.95

/opt/anaconda3/lib/python3.12/site-packages/astropy/cosmology/flrw/w0wacdm.py:195: RuntimeWarning: invalid value encountered in scalar divide
  return zp1 ** (3 * (1 + self._w0 + self._wa)) * exp(-3 * self._wa * z / zp1)


In [38]:
param

theory                                                              eft
alphaB0                                                             0.1
alphaM0                                                             0.3
H0                                                                 70.0
Om_m                                                                0.3
T_cmb                                                             2.726
N_eff                                                             3.044
w0                                                                 -1.0
wa                                                                  0.0
base                                                                 ./
extra                                                              test
aexp                                                                  1
boxlen                                                              100
npart                                                          1

In [39]:
import eftcalcs

In [40]:
eft_quantities = eftcalcs.geteft(param,tables)

In [41]:
potential = np.empty(0, dtype=np.float32)
density = np.random.normal(0,10,(256,256,256)).astype(np.float32)
h = 1./256

param["alphaB"] = eft_quantities[0]
param["alphaM"] = eft_quantities[1]
param["C2"] = eft_quantities[2]
param["C4"] = eft_quantities[3]
param["H"] = eft_quantities[4]
param["M"] = eft_quantities[5]

In [42]:
import solver

In [43]:
phi = solver.initialise_potential(potential,density,h,param,tables)

In [44]:
phi = solver.get_additional_field(phi,density,h,param,tables)

### initialise_potential and get_additional_field work: 13 Jan 25

In [ ]:
phi.shape

In [ ]:
phi